id: I55B13121
legacy_id: P000645
ocr_import_info:
  bdrc_scan_id: W30150
  source: bdrc
  ocr_info:
    timestamp: '2020-03-28T16:12:22'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T11:21:19.633696+00:00'
last_modified: 2022-09-03 19:21:36.907473
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W30150
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW30150
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: འབྲུག་པའི་རྗེ་མཁན་པོ་ངག་དབང་ཕྲིན་ལས་དང་། ཤེས་རབ་རྒྱལ་མཚན། ཡོན་ཏན་རྒྱལ་མཚན་གསུམ་གྱི་རྣམ་ཐར།
  author: ཞབས་དྲུང་ཐུགས་སྤྲུལ ༠༤་འཇིགས་མེད་ནོར་བུ།
statistics:
  ocr_word_mean_confidence_index: 0.7003232344113965
  ocr_word_median_confidence_index: 0.75
quality: null
bases:
  I6062:
    source_metadata:
      id: http://purl.bdrc.io/resource/I6062
      total_pages: 606
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I6062.txt
    statistics:
      ocr_word_median_confidence_index: 0.75
      ocr_word_mean_confidence_index: 0.7003232344113965
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
