id: I55B13121
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T16:15:53+00:00'
last_modified: '2022-06-07T12:32:47.181916+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W30150
  title: འབྲུག་པའི་རྗེ་མཁན་པོ་ངག་དབང་ཕྲིན་ལས་དང་། ཤེས་རབ་རྒྱལ་མཚན། ཡོན་ཏན་རྒྱལ་མཚན་གསུམ་གྱི་རྣམ་ཐར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '9695':
      image_group_id: I6062
      title: ''
      total_pages: 606
      order: 1
      base_file: 9695.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
