id: opecha:P000645
initial_creation_type: ocr
source_metadata:
  id: bdr:W30150
  title: འབྲུག་པའི་རྗེ་མཁན་པོ་ངག་དབང་ཕྲིན་ལས་དང་། ཤེས་རབ་རྒྱལ་མཚན། ཡོན་ཏན་རྒྱལ་མཚན་གསུམ་གྱི་རྣམ་ཐར།
  volume: ''
  author: ''
