id: P000645
initial_creation_type: ocr
source_metadata:
  id: bdr:W30150
  title: འབྲུག་པའི་རྗེ་མཁན་པོ་ངག་དབང་ཕྲིན་ལས་དང་། ཤེས་རབ་རྒྱལ་མཚན། ཡོན་ཏན་རྒྱལ་མཚན་གསུམ་གྱི་རྣམ་ཐར།
  author: ''
  volumes:
    a92f728077124a66a4f5b80ccb1b2254:
      image_group_id: I6062
      title: ''
      volume_number: 1
      total_pages: 606
